### ISSUE TITLE
SSH config management

### ISSUE THREAD

**Issue by MiLk** [AerisCloud/AerisCloud#27]
I would like to have my ssh config file dynamically generated using my dynamic inventory and used by ansible when running `cloud provision`.

I use the following config:

```
# ssh.cfg
Host *
  ForwardAgent no
  GSSAPIAuthentication no

Host <bastion public ip>
  Port 22
  User <standard user>
  IdentityFile ~/.ssh/...

Host <bastion host name>
  HostName <bastion public ip>
  Port 22
  User <user with no login permissions>
  IdentityFile ~/.ssh/...

Host 10.10.*
  Port 22
  User <standard user>
  IdentityFile ~/.ssh/...
  ProxyCommand ssh -F <custom ssh config path>-W %h:%p <bastion host name>
```

``` ini
# ansible.cfg
[ssh_connection]
pipelining=True
ssh_args = -F <custom ssh config path> -o ControlMaster=auto -o ControlPersist=30m
```

And then run `ANSIBLE_CONFIG=./ansible.cfg cloud provision`

I would like `cloud` to:
- generate the ssh config file from a template
- add the `-F` option to the ssh_args
- work without having me to deal with the `ANSIBLE_CONFIG` variable

**Comment by christopherobin** [comment]
One way to have the auto-generation not use any config is to override the main `~/.ssh/config` file, as such the best way to allow for custom config is to pull extra config from the `.ssh/conf.d` folder and merge it at the beginning. I have a tool that works that way (generates ssh config from cloud resources) and my folder looks like:

```
$ ls -1 ~/.ssh/conf.d                                                                                                                                                                                                       
00-global.conf
05-office.conf
10-aur4.conf
10-home.conf

```

**Comment by MiLk** [comment]
I ended up using https://github.com/moul/advanced-ssh-config and it's good enough.
Integration with AC is not required.
