### ISSUE TITLE
Request: Structure organizations around GitHub

### ISSUE THREAD

**Issue by stelcheck** [AerisCloud/AerisCloud#6]
Namely:

```
# github:MyCompany/aeriscloud-organization
cloud organization init MyCompany
# github: MyCompany/myfriend-aeriscloud-organization
cloud organization install MyCompany/myfriend
# Custom source, like now
cloud organization install name source
cloud organization init name git@github.com:Custom/repo.git
```

In .aeris.yml:

```
organization: MyCompany
organization: MyCompany/myfriend
organization: name <git@github.com:Custom/repo.git>
```

This would allow us to:
1. Center primarily around GitHub without locking you to it
2. Do many additional check (does the repository already exist?)
3. Set up local git repository instead of having to manually `git remote add...`
4. Make sure that the right organization is being used for an `aeris` project (by checking the organization git origin)

Overall, this would simplify documentation and use for most general use cases.

cc @christopherobin @MiLk

**Comment by MiLk** [comment]
Possible workflow for `organization init`:
`cloud organization init MyCompany`
- if GH integration is enabled
  - check if the repo exists
    - not-empty > fail / install?
    - empty > use that repo
  - not exists > check if the organization exists
    - exists > ask to create a repo if has permissions
  - else standard behaviour

Add a message to explain what to do after init.

**Comment by stelcheck** [comment]
Reopening.
1. install doesn't seem to be done. 
2. remote doesn't actually get set
3. `cloud organization init name` should be for GitHub only; non-github should be forced to provide a repository (I had suggested to add a --local for local-only organizations, but I think in the end we came to the conclusion that you should always store organizations somewhere...)

**Comment by MiLk** [comment]
Remote is set only if the repo is actually present on GitHub.
Was the repository already created on GitHub?

About 3. I'm not sure we should enforce the user.
What does it actually bring to AerisCloud to disallow the user to run `cloud organization init name` without setting up a remote?

**Comment by MiLk** [comment]
New flow proposal:
- if remote is not specified
  - check if GH integration is enabled
    - check if member of the organization
      - check if repo exists
        - generate a remote URL
      - if repo doesn't exist
        - give instructions to create the repo
        - confirm message to continue or abort
    - if not member of the organization
      - print warning because not able to check the existence of the repo
      - confirm message to continue or abort
- if no remote is defined
  - fatal
- check if the organization is already on the disk
- download the sample organization tarball
- extract the tarball in the newly created directory
- remove the tarball
- git init
- move the user to the new directory
- print message to say that the organization has been created
- run gallaxy install
- set the remote
- print message to say that the remote has been set
- print instructions about what to do (edit, add, commit, push? link to doc?)

**Comment by stelcheck** [comment]
Sounds good to me. Would be nice to print something on screen letting the user know that the cwd has been changed.
